Основной сервис
max-vassiliev/java-explore-with-me pull request #4
Opened 2023-04-30 21:53 UTC by max-vassiliev

Добавлен модуль `main-svc` с основной функциональностью приложения `Explore With Me`.

2023-05-01 18:25 UTC, AnastasiyaFomkina requested changes
Отличная работа! Молодец

2023-05-01 18:25 UTC, AnastasiyaFomkina commented on main-svc/src/main/java/ru/practicum/ewm/compilation/repository/EventCompilationRepository.java
> +        for (Map<String, Object> row : rows) {
Нужно переписать с помощью  stream api

2023-05-01 18:25 UTC, AnastasiyaFomkina commented on main-svc/src/main/java/ru/practicum/ewm/compilation/service/impl/AdminCompilationServiceImpl.java
> +    private Compilation updateFields(Compilation compilation, UpdateCompilationRequest request) {
Можно переписать с помощью mapstruct. Хорошей стать, как это сделать, найти не удалось, попробую объяснить самостоятельно.
В первую очередь нам нужно объявить сам метод
```
Compilation update(UpdateCompilationRequest recipient, @MappingTarget Compilation donor);
```
Аннотация `@MappingTarget` показывает в какую сущность будут маппится изменения. 
По хорошему, можно вообще сделать метод `void`, так как сущность с `@MappingTarget` и так уже будет содержать все изменения:
```
void update(UpdateCompilationRequest recipient, @MappingTarget Compilation donor);
```
Соответственно, нужно научить метод обрабатывать null, для этого в настройках маппера, нужно будет добавить параметр `nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE`
Тогда получатся следующие настройки маппера:
```
@Mapper(
    componentModel = "spring",
    nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE
)
```
После всех доработок, нужно будет перегенерить проект и можно будет пользоваться сгенерированным методм

2023-05-01 18:25 UTC, AnastasiyaFomkina commented on main-svc/src/main/java/ru/practicum/ewm/request/dto/EventRequestStatusUpdateRequest.java
> +    RequestStatus status;
Не хватает модификаторов доступа

2023-05-01 18:25 UTC, AnastasiyaFomkina commented on main-svc/src/main/java/ru/practicum/ewm/request/dto/EventRequestStatusUpdateResult.java
> +    List<ParticipationRequestDto> rejectedRequests;
Не хватает модификаторов доступа

2023-05-01 18:25 UTC, AnastasiyaFomkina commented on main-svc/src/main/resources/schema.sql
> +);
_Опционально_
Предлагаю попробовать добавить [индексы](https://tproger.ru/articles/indeksy-v-postgresql/), чтобы ускорить поиск

2023-05-01 21:10 UTC, max-vassiliev commented on main-svc/src/main/java/ru/practicum/ewm/compilation/service/impl/AdminCompilationServiceImpl.java
> +    private Compilation updateFields(Compilation compilation, UpdateCompilationRequest request) {
А вот и готовая статья) спасибо за подробное объяснение!

2023-05-01 21:11 UTC, max-vassiliev commented on main-svc/src/main/resources/schema.sql
> +);
Спасибо огромное за этот материал!🔥 Сейчас, боюсь, не хватит времени нормально это освоить. Но хочется попробовать, попробую воплотить в будущем.

2023-05-02 07:32 UTC, AnastasiyaFomkina approved these changes

2023-05-02 13:26 UTC, merged